SELECT COUNT(*)
FROM CUSTOMER
WHERE C_CUSTKEY IN 
(
    SELECT C_CUSTKEY
    FROM CUSTOMER C 
    INNER JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
    WHERE C_CUSTKEY IN
    (
        SELECT DISTINCT(O_CUSTKEY)  
        FROM ORDERS 
    )
    AND O.O_COMMENT LIKE '%special request%'
    EXCEPT
    SELECT C_CUSTKEY
    FROM CUSTOMER 
    WHERE C_CUSTKEY IN
    (
        SELECT DISTINCT(O_CUSTKEY)
        FROM ORDERS 
        WHERE O_COMMENT LIKE '%unusual package%'
    )
);