SELECT DISTINCT(N.N_NAME), SUM(L.L_QUANTITY)
FROM LINEITEM L
INNER JOIN ORDERS O ON O.O_ORDERKEY = L.L_ORDERKEY
INNER JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
INNER JOIN NATION N ON N.N_NATIONKEY = C.C_NATIONKEY
GROUP BY N.N_NAME
ORDER BY SUM(L.L_QUANTITY) DESC
LIMIT 10;