SELECT COUNT(*)
FROM CUSTOMER
WHERE C_CUSTKEY IN 
(
    SELECT C_CUSTKEY
    FROM CUSTOMER 
    EXCEPT
    SELECT C_CUSTKEY
    FROM CUSTOMER 
    WHERE C_CUSTKEY IN
    (
        SELECT DISTINCT(O_CUSTKEY)
        FROM ORDERS 
    )
);